### ISSUE TITLE
01- Coordonnées cylindriques

### ISSUE THREAD

**Issue by DagnyT** [c-hebert/MecaDRIL#6]
3D model of cylindrical coordinates, like:

http://www.sciences.univ-nantes.fr/sites/genevieve_tulloue/Meca/Cinematique/coord_cylindriques.php

**Comment by arashgmn** [comment]
I'm using `plotly` for this. The problem with it is that you cannot have it offline, the api just sends some information to plotly's server and then the plot is received in the notebook. Is it ok?

**Comment by DagnyT** [comment]
Hello Arash,

Could you please investigate other options, we don't want to rely on external commercial software. 

About upload - you can upload the notebook here: https://github.com/c-hebert/MecaDRIL/tree/master/01-Cinematique

**Comment by arashgmn** [comment]
The updated version of the notebook has pushed. The rotation can be done easily using `mpl_toolkits` and `%matplotlib notebook`. All irrelevant approaches using other packages have been cleared up.

**Comment by arashgmn** [comment]
in the newest version of matplotlib (3.1), the command `ax.set_aspect('equal')` [is temporarily returning](https://matplotlib.org/3.1.0/api/api_changes.html#equal-aspect-axes-disabled) a `NotImplemenedError` because of [this](https://github.com/matplotlib/matplotlib/issues/1077/#issuecomment-14006279) issue. This doesn't affect our application though and if we use the lower version, everything should work.
